# Generated by Django 4.0.6 on 2022-07-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImgName', models.CharField(max_length=50)),
                ('ImgURL', models.ImageField(blank=True, upload_to='images/')),
                ('ImgDetails', models.TextField(default=None, max_length=1500)),
            ],
        ),
    ]
