# Generated by Django 4.0.6 on 2022-07-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='ImgURL',
            field=models.URLField(),
        ),
    ]
